sudo: required
services:
    - docker

before_install:
    - docker build -t mitulshah96/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true mitulshah96/react-test npm test -- --coverage

after_success:
    - docker  build -t mitulshah96/multi-client ./client
    - docker  build -t mitulshah96/multi-nginx ./nginx
    - docker  build -t mitulshah96/multi-server ./server
    - docker  build -t mitulshah96/multi-worker ./worker
    #Log in to docker cli
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --pasword-stdin
    #Take those images and push them to docker hub
    - docker push mitulshah96/multi-client
    - docker push mitulshah96/multi-nginx
    - docker push mitulshah96/multi-server
    - docker push mitulshah96/multi-worker
